model_name: ["seq_sy_conv_3lv"]
batch_size: [32]
lr: loguniform(1e-6, 1e-3)
weight_decay: loguniform(1e-6, 1e-3)
arch_oc: ["SchemeASyLevel"]
arch_embs: [64]
arch_conv: randint(64, 256)
arch_l1: randint(16, 48)
arch_do: uniform(0, 0.5)
arch_crf: [1]