model_name: ["seq_sy_ch_lstm"]
batch_size: [32]
lr: loguniform(1e-4, 1e-3)
weight_decay: loguniform(1e-6, 1e-3)
arch_oc: ["BI"]
arch_bi: [1]
arch_embc: [32]
arch_embt: [32]
arch_embs: [64]
arch_cells: randint(128, 512)
arch_do: uniform(0, 0.5)
arch_l1: randint(16, 48)
arch_crf: [1]