model_name: ["seq_ch_lstm"]
batch_size: [128]
lr: loguniform(1e-6, 1e-3)
weight_decay: loguniform(1e-6, 1e-3)
arch_oc: ["BI"]
arch_bi: [1]
arch_embc: [32]
arch_embt: [32]
arch_cells: randint(64, 512)
arch_l1: randint(16, 48)