model_name: ["seq_sy_conv_3lv"]
batch_size: [128]
lr: loguniform(1e-4, 1e-3)
weight_decay: loguniform(1e-6, 1e-3)
arch_oc: ["BI"]
arch_embs: [64]
arch_conv: randint(128, 256)
arch_l1: randint(16, 48)
arch_do: uniform(0, 0.5)