model_name: ["seq_sy_lstm"]
batch_size: [32]
lr: loguniform(1e-6, 1e-3)
weight_decay: loguniform(1e-6, 1e-3)
arch_oc: ["SchemeB"]
arch_bi: [1]
arch_embs: [64]
arch_cells: randint(64, 512)
arch_l1: randint(16, 48)
arch_crf: [1]