model_name: ["seq_sy_ch_conv_3lv"]
batch_size: [32]
arch_embc: [32]
arch_embt: [32]
arch_embs: [64]
lr: [4.65e-04]
weight_decay: [1.06e-06]
arch_conv: [137]
arch_l1: [42]
arch_do: [0.0929509300900459]
arch_oc: ["SchemeB"]