model_name: ["seq_sy_ch_lstm"]
batch_size: [32]
lr: [7.86e-05]
weight_decay: [1.78e-06]
arch_oc: ["SchemeB"]
arch_bi: [1]
arch_embc: [32]
arch_embt: [32]
arch_embs: [64]
arch_cells: [257]
arch_l1: [21]